app/blueprints/main/models.py
from app import db, login_manager
from flask_login import UserMixin
from datetime import datetime

class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(50), unique=True)
    username = db.Column(db.String(50))
    password = db.Column(db.String(200))
    first_name = db.Column(db.String(50))
    last_name = db.Column(db.String(50))

class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(250))
    body = db.Column(db.String(1200))
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    date_created = db.Column(db.DateTime, default=datetime.utcnow)

# Create a "car" model, with the same columns we had earlier
# name, year, selling_price, user_id
class Car(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100))
    year = db.Column(db.Integer)
    selling_price = db.Column(db.Float)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

app/__init__.py
from flask import Flask
from config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager

db = SQLAlchemy()
migrate = Migrate()
login_manager = LoginManager()

app = Flask(__name__)
# Connecting our config class and our flask application
app.config.from_object(Config)

db.init_app(app)
migrate.init_app(app, db)
login_manager.init_app(app)

from app.blueprints.main import bp as main_bp
app.register_blueprint(main_bp)

from app.blueprints.api import bp as api_bp
app.register_blueprint(api_bp)

from app.blueprints.auth import bp as auth_bp
app.register_blueprint(auth_bp)

app/blueprints/api/__init__.py
from flask import Blueprint

bp = Blueprint('api', __name__,  url_prefix="/api")

from . import models, routes

app/blueprints/api/routes.py
from . import bp as app
from flask import render_template

# Routes that return JSON
user_data = { # Mock database data
    'lucasl': {
        'user_id': 0,
        'name': 'Lucas',
        'favoriteColor': 'blue',
        'posts': [
            {
                'id': 0,
                'title': 'This is post 1',
                'body': 'This is the text for the post'
            },
            {
                'id': 1,
                'title': 'This is post 2',
                'body': 'This is the text for the post'
            },
            {
                'id': 2,
                'title': 'This is post 3',
                'body': 'This is the text for the post'
            }
        ]
    },
    'christophert': {
        'user_id': 1,
        'name': 'Christopher',
        'favoriteColor': 'orange',
        'posts': [
            {
                'id': 3,
                'title': 'This is post 4',
                'body': 'This is the text for the post'
            },
            {
                'id': 4,
                'title': 'This is post 5',
                'body': 'This is the text for the post'
            },
            {
                'id': 5,
                'title': 'This is post 6',
                'body': 'This is the text for the post'
            }
        ]
    },
    'joelc': {
        'user_id': 2,
        'name': 'Joel',
        'favoriteColor': 'red',
        'posts': [
            {
                'id': 6,
                'title': 'This is post 7',
                'body': 'This is the text for the post'
            },
            {
                'id': 7,
                'title': 'This is post 8',
                'body': 'This is the text for the post'
            },
            {
                'id': 8,
                'title': 'This is post 9',
                'body': 'This is the text for the post'
            }
        ]
    }
}

# Create a route to get all user information
@app.route('/users/')
def users():
    return user_data

# Create a route to get user information based on their username
@app.route('/user/username/<username>')
def user(username):
    if username not in user_data:
        return 'User not found'

    return user_data[username]

# Create a route to get user information based on their id
@app.route('/user/id/<id>')
def user_by_id(id):
    for key, user in user_data.items():
        if user['user_id'] == int(id):
            return user

    return 'User not found'


car_data = {
    0: {
        "name": "Maruti Swift Dzire VDI",
        "year": 2014,
        "selling_price": 450000
    },
    1: {
        "name": "Skoda Rapid 1.5 TDI Ambition",
        "year": 2014,
        "selling_price": 370000
    },
    2: {
        "name": "Honda City 2017-2020 EXi",
        "year": 2006,
        "selling_price": 158000
    }
}

# Create a route that lists all of the cars in car_data
@app.route('/cars')
def cars():
    return car_data

@app.route('/cars/year/<year>')
def car_by_year(year):
    car_result = {}

    for key, car in car_data.items():
        if car['year'] == int(year):
            car_result[key] = car

    return car_result

@app.route('/cars/id/<id>')
def car_by_id(id):
    if int(id) not in car_data:
        return 'Car not found'

    return car_data[int(id)]

app/blueprints/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__,  url_prefix="/")

from . import models, routes

app/blueprints/main/routes.py
from . import bp as app
from flask import render_template, request, redirect, url_for, flash
from app.blueprints.main.models import User, Post
from app import db
from flask_login import current_user

# Routes that return/display HTML

@app.route('/')
def home():
    posts = Post.query.all()

    return render_template('home.html', user=current_user, posts=posts)

@app.route('/about')
def about():
    return render_template('about.html')

@app.route('/contact')
def contact():
    return render_template('contact.html')

@app.route('/post', methods=['POST'])
def create_post():
    post_title = request.form['title']
    post_body = request.form['body']
    
    new_post = Post(title=post_title, body=post_body, user_id=current_user.id)

    db.session.add(new_post)
    db.session.commit()

    flash('Post added succesfully', 'success')
    return redirect(url_for('main.home'))

app/templates/about.html
{% extends './partials/layout.html' %}

{% block content %}
<!-- JINJA -->
<h1>about</h1>
{% endblock content %}

app/templates/contact.html
{% extends './partials/layout.html' %}

{% block content %}
<!-- JINJA -->
<h1>contact</h1>
{% endblock content %}

app/templates/home.html
{% extends './partials/layout.html' %}

{% block content %}

<!-- JINJA -->
<h1>Home</h1>
<p> Welcome {{ user['first_name'] }} {{ user['last_name']}} </p>
<h2>Create Post</h2>

<form action=" {{ url_for('main.create_post')}}" method="POST" class="my-2">
    <div class="form-group">
      <label for="title">Title</label>
      <input type="text" class="form-control" id="title" name="title">
    </div>
    <div class="form-group">
        <label for="body">body</label>
        <input type="text" class="form-control" id="body" name="body">
      </div>

    <button type="submit" class="btn btn-primary">Submit</button>
  </form>

{% for post in posts %}
<div class="'card">
    <div class="card-header">
        {{ post['title']}}
    </div>
    <div class='card-body'>
        <p class="'card-text"> {{ post['body'] }}</p>
    </div>
</div>

{% endfor%}
{% endblock content %}

app/templates/login.html
{% extends './partials/layout.html' %}

{% block content %}
<h1>Login</h1>
<form action="{{ url_for('auth.login') }}" method="POST">
    <div class="form-group">
        <label for="inputEmail">Email address</label>
        <input type="email" class="form-control" id="inputEmail" name="inputEmail" aria-describedby="emailHelp">
        <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
    </div>
    <div class="form-group">
        <label for="inputPassword">Password</label>
        <input type="password" class="form-control" id="inputPassword" name="inputPassword">
    </div>
    <p><small>Don't have an account? <a href="{{ url_for('auth.register') }}">Register here.</a></small></p>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock content %}

app/templates/partials/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
        integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
</head>

<body>
    <header class="mb-5">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="#">Fakebook</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{{ url_for('main.home') }}">Home <span
                                class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('main.about') }}">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('main.contact') }}">Contact</a>
                    </li>
                </ul>
                <ul class="navbar-nav">
                    {%  if not current_user.is_authenticated   %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.register') }}">Register</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>

    <main class="container">
        {% with messages = get_flashed_messages(with_categories=True) %}
            {% if messages %}
                <ul class=flashes>
                {% for category, message in messages %}
                <div class="alert alert-{{ category }}" role="alert">
                    {{ message }}
                </div>
                {% endfor %}
                </ul>
            {% endif %}
        {% endwith %}
        <!-- THIS IS WHERE WE WILL PUT EACH PAGE'S CONTENT -->
        {% block content %}{% endblock content %}
    </main>

    <!-- <footer>
        This is a footer
    </footer> -->
</body>

</html>

app/templates/register.html
{% extends './partials/layout.html' %}

{% block content %}
<h1>Register</h1>
<form action="{{ url_for('auth.register') }}" method="POST">
    <div class="form-group">
        <label for="inputEmail">Email address</label>
        <input type="email" class="form-control" id="inputEmail" name="inputEmail" aria-describedby="emailHelp">
        <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
    </div>
    <div class="form-group">
        <label for="inputUsername">Username</label>
        <input type="text" class="form-control" id="inputUsername" name="inputUsername">
    </div>
    <div class="form-group">
        <label for="inputFirstName">First Name</label>
        <input type="text" class="form-control" id="inputFirstName" name="inputFirstName">
    </div>
    <div class="form-group">
        <label for="inputLastName">Last Name</label>
        <input type="text" class="form-control" id="inputLastName" name="inputLastName">
    </div>
    <div class="form-group">
        <label for="inputPassword">Password</label>
        <input type="password" class="form-control" id="inputPassword" name="inputPassword">
    </div>
    <div class="form-group">
        <label for="inputPasswordConfirm">Confirm Password</label>
        <input type="password" class="form-control" id="inputPasswordConfirm" name="inputPasswordConfirm">
    </div>
    <p><small>Already have an account? <a href="{{ url_for('auth.login') }}">Login here.</a></small></p>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock content %}